# Generated by Django 6.0.1 on 2026-05-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_complexity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Решение', 'verbose_name_plural': 'Решения учеников'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='output',
            field=models.TextField(blank=True, verbose_name='Вывод'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Пройдено'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='day_index',
        ),
    ]
