# Generated by Django 6.0.1 on 2026-05-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_submission_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complexity', 'id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
